{% set name = "html5tagger" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/html5tagger-{{ version }}.tar.gz
  sha256: 84fa3dfb49e5c83b79bbd856ab7b1de8e2311c3bb46a8be925f119e3880a8da9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - html5tagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanic-org/html5tagger
  summary: Pythonic HTML generation/templating (no template files)
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
