schema_version: 1

context:
  name: html5tagger
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/html5tagger-${{ version }}.tar.gz
  sha256: 0dee3c9054443930e9a3225edcc810b6df76c0aeabfee463e9437a90a1ac1624

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - html5tagger
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Pythonic HTML generation/templating (no template files)
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/sanic-org/html5tagger

extra:
  recipe-maintainers:
    - thewchan
